#!/usr/bin/env bash
#get servers info
if [ "$1" ]
then
dig "$1.gtexk.tech"|grep -A1 "ANSWER SECTION"|awk 'END{print}'|
        awk  -v A="$1" -F " " '{print "The subdomain " A " is a " $4 " record and points to "$5}'
else
        dig "www.gtexk.tech"|grep -A1 "ANSWER SECTION"|awk 'END{print}'|
        awk  -v A="www" -F " " '{print "The subdomain " A " is a " $4 " record and points to "$5}'
        dig "lb-01.gtexk.tech"|grep -A1 "ANSWER SECTION"|awk 'END{print}'|
        awk  -v A="lb-01" -F " " '{print "The subdomain " A " is a " $4 " record and points to "$5}'
        dig "web-01.gtexk.tech"|grep -A1 "ANSWER SECTION"|awk 'END{print}'|
        awk  -v A="web-01" -F " " '{print "The subdomain " A " is a " $4 " record and points to "$5}'
        dig "web-02.gtexk.tech"|grep -A1 "ANSWER SECTION"|awk 'END{print}'|
        awk  -v A="web-02" -F " " '{print "The subdomain " A " is a " $4 " record and points to "$5}'
fi
