#!/usr/bin/env bash
#script to installl and configure nginx
apt-get update
apt-get install -y nginx
mkdir -p /etc/www/nginx/html
touch /etc/www/nginx/html/index.html
echo "Hello World!" > /etc/www/nginx/html/index.html
truncate -s 0 /etc/nginx/sites-available/default
cat <<END>> /etc/nginx/sites-available/default
server {
	listen   80 default_server;
	listen   [::]:80 default_server;
	root     /etc/www/nginx/html;
	index    index.html index.htm;
}
END
service nginx restart
