#!/usr/bin/env bash
#script to installl and configure nginx
apt-get update
apt-get install -y nginx
mkdir /var/www/nginx/html
echo "Hello World" >/var/www/nginx/html/index.html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html;
	}">/etc/nginx/site-available/default
service nginx restart
