#!/usr/bin/env bash
# managing script demo
if [ "$1" == "start" ]
then
	./manage_my_process &
	echo "$$">/var/run/my_process.pid
	echo "manage_my_process started"
	exit
elif [ "$1" == "stop" ]
then
	kill "$(pgrep -f /manage_my_process)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
	exit
elif [ "$1" == "restart" ]
then 
	kill "$(pgrep -f /manage_my_process)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process restarted"
	exit
else
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi
