#!/usr/bin/env bash
# configure nginx to run as user nginx
sudo sed -i '/*user www-data*/c\user nginx;\n' /etc/nginx/nginx.conf
sudo sed -i '/*listen   80 default_server;*/c\       listen   8080 default_server;\n' /etc/nginx/sites-available/default
sudo sed -i '/*listen   [::]:80 default_server;*/c\    listen   [::]:8080 default_server;\n' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx restart
